name: SmartGrid AI Retraining

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1"

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

            - name: Configure DagsHub authentication
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user asinsyed24
          dvc remote modify origin --local password "$DAGSHUB_TOKEN"

      - name: Pull versioned dataset
        run: |
          dvc pull data/raw/household_power_consumption.zip.dvc --force

      - name: Extract dataset
        run: |
          unzip -o data/raw/household_power_consumption.zip -d data/raw/

      - name: Run preprocessing
        run: |
          python src/preprocessing.py

      - name: Train and select best model
        run: |
          python src/train.py

      - name: Verify trained model
        run: |
          test -f models/best_energy_model.pkl
          echo "SmartGrid AI retraining completed successfully"

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: smartgrid-energy-model
          path: models/best_energy_model.pkl